//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisRptBanco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMovCtaxBco
    {
        public int IdMovCtaxBco { get; set; }
        public Nullable<int> IdCtaxBco { get; set; }
        public Nullable<System.DateTime> dFecIng { get; set; }
        public Nullable<System.DateTime> dFecOpe { get; set; }
        public string cNroOpe { get; set; }
        public string cConcepto { get; set; }
        public Nullable<decimal> nImporte { get; set; }
        public string cDestino { get; set; }
        public string cNroFac { get; set; }
        public Nullable<decimal> nSalFin { get; set; }
        public string cEstado { get; set; }
    
        public virtual MCtaxBco MCtaxBco { get; set; }
    }
}
