//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisRptBanco.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCtaxBco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MCtaxBco()
        {
            this.DMovCtaxBco = new HashSet<DMovCtaxBco>();
        }
    
        public int IdCtaxBco { get; set; }
        public string cDesBco { get; set; }
        public string cNroCta { get; set; }
        public string cTipIns { get; set; }
        public string cEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMovCtaxBco> DMovCtaxBco { get; set; }
        public virtual TTipIns TTipIns { get; set; }
    }
}
